### PR TITLE
Wordlist with decimals

### PR DESCRIPTION
**Pull request by moneymanolis**
I made an additional make-wordlist-py-file where I replaced the hex values with decimal values. Could be useful for the offline seed generation projects etc. Numbers start with 1 and go until 2048. 

Looks like this:

First page:
grafik

... pages 2 and 3 ...

last page:
grafik

### CODE REVIEW

**Comment by doc-hex** [comment]
- make it output to a different filename, perhaps `wordlist-decimal.pdf`
- undo your change to `.gitignore`, I like committing the final product so can be downloaded by non programmers
- could this just be an argument to the original program, perhaps: `--decimal` on the command line?

**Comment by moneymanolis** [comment]
Thanks for the review. Sure, I'll do that.

**Comment by moneymanolis** [comment]
Tried to address all your points in the latest commit https://github.com/Coldcard/wordlist-paper/pull/1/commits/c4f393fe91ab457ea100b41c8a9b6e48f4e47e5b. 
Let me know what you think.

**Comment by k9ert** [comment]
What's blocking the merge of this?

**Comment by doc-hex** [comment]
Sorry lost track of this PR. Thanks for the contribution!

**Pull request merged**
